# Generated by Django 4.1.4 on 2022-12-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_rename_title_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="default.jgp", null=True, upload_to=""
            ),
        ),
    ]
